### PR TITLE
Merge black

### PR DESCRIPTION
**Pull request by jschwartzentruber**
I recently enabled black upstream, and the merge was substantial...

Note that I removed your requirements file too since we're not using those files anymore. We run mypy under tox to get a clean virtualenv, and to make a later pre-commit hook easier (eg. [lithium](https://github.com/MozillaSecurity/lithium/blob/master/.pre-commit-config.yaml#L52)). To run locally, run `tox -e mypy -- .` Let me know if this breaks anything for you.

I also noticed you aren't enabling the django-stubs and drf-stubs mypy plugins (I added them to pyproject.toml but commented out). When I did enable them I got errors about the problems in */models.py where you're changing fields to `str()` or `int()`. These likely need to remain as django model field types, but I would see if the django-stubs plugin solves all that for you.

### CODE REVIEW

**Comment by nth10sd** [comment]
Sorry I only saw this now, thanks!

**Comment by nth10sd** [comment]
Yes, I got `tox` to work, I'll bump the mypy version though, as well as the other stubs packages.

I had the django-stubs and drf-stubs in `server/requirements3.7.txt` that was removed, fwiw. I'll add some others that I've been using in too.

**Comment by jschwartzentruber** [comment]
> I had the django-stubs and drf-stubs in `server/requirements3.7.txt` that was removed, fwiw. I'll add some others that I've been using in too.

Most of the stub requirements weren't necessary, since `mypy --install-types` will install them in tox as needed. What I meant was the django & drf mypy *plugins* included in those packages. The plugins must be enabled in the `[tool.mypy]` section of pyproject.toml.

**Comment by nth10sd** [comment]
Ooh I get what you mean now, I'll turn them on.

**Pull request merged**
